### PR TITLE
set active state to true

### PR DESCRIPTION
**Pull request by mklooss**

### CODE REVIEW

**Comment by riker09** [comment]
This issue is now open for more than a year. No comment, no merge, no nothing?

**Comment by progammer-rkt** [comment]
@riker09 Is this "Issue" is a big deal at all ? I believe this extension is going to use by developers mainly. So they should know how to turn on an extension :)

**Comment by mklooss** [comment]
@progammer-rkt yes, when ur using git submodules in your projekt ;-)
because you can not edit an submodule

**Comment by riker09** [comment]
I agree, it is mainly used by developers, but why shouldn't our life a little bit less complicated? ;)
Besides, @mklooss has a good point. I want to be able to use this module OOB, no manual edit should be necessary.

**Pull request merged**
